version: '3.8'

services:
  api:
    build: .
    container_name: qlvpp-api
    ports:
      - "5000:8080"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=QLVPP_DB;User=sa;Password=${DB_SA_PASSWORD};TrustServerCertificate=True
      - Redis__Host=redis
      - Redis__Port=6379
      
      # THÊM MỚI: Cung cấp mật khẩu Redis cho API của bạn
      - Redis__Password=${REDIS_PASSWORD}
    restart: on-failure

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: qlvpp-db
    environment:
      - ACCEPT_EULA=Y
      - TZ=Asia/Ho_Chi_Minh
      - MSSQL_PID=Developer
      - MSSQL_SA_PASSWORD=${DB_SA_PASSWORD}
    ports:
      - "14333:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      # SỬA Ở ĐÂY: Dùng biến ${DB_SA_PASSWORD} thay vì hard-code
      test: >
        /bin/bash -c "
        /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P '${DB_SA_PASSWORD}' -Q 'SELECT 1' -C
        || /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P '${DB_SA_PASSWORD}' -Q 'SELECT 1'
        "
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 40s
    restart: always

  redis:
    image: redis:latest
    container_name: qlvpp-redis
    
    command: redis-server --requirepass ${REDIS_PASSWORD}
    
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  mssql_data:
  redis_data: